### ISSUE TITLE
Routing option to auto-validate signature

### ISSUE THREAD

**Issue by kbond** [kbond/signed-url-bundle#2]
```yaml
my_route:
    path: /some-path
    controller: App\Controller\SomeController
    options:
        signed: true
```
